import { StyleSheet } from "react-native";
import theme from "../theme";

export const modalStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: theme.colors.background.overlay,
    justifyContent: "center",
    alignItems: "center",
  },
  overlayTouchable: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  modalContent: {
    width: "88%",
    maxWidth: 380,
    backgroundColor: theme.colors.background.primary,
    borderRadius: 24,
    padding: 28,
    alignItems: "center",
    ...theme.shadows.xl,
  },
  modalDecoration: {
    width: 50,
    height: 4,
    backgroundColor: theme.colors.primary.beige,
    borderRadius: 2,
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: theme.typography.fontWeight.light,
    color: theme.colors.text.primary,
    marginBottom: 6,
    letterSpacing: 0.5,
  },
  modalSubtitle: {
    fontSize: 14,
    color: theme.colors.text.tertiary,
    marginBottom: 28,
    letterSpacing: 0.3,
  },
  modalButton: {
    width: "100%",
    height: 72,
    borderRadius: 16,
    marginVertical: 6,
    overflow: "hidden",
    shadowColor: theme.colors.primary.darkBrown,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  modalButtonText: {
    color: theme.colors.primary.cream,
    fontWeight: theme.typography.fontWeight.semibold,
    fontSize: 16,
    letterSpacing: 0.3,
    marginBottom: 2,
  },
  modalButtonSubtext: {
    color: "rgba(250, 248, 245, 0.75)",
    fontSize: 12,
    letterSpacing: 0.2,
  },
  primaryButton: {
    marginBottom: 10,
  },
  buttonGradient: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  buttonIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(250, 248, 245, 0.9)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 14,
  },
  buttonTextContainer: {
    flex: 1,
  },
  cancelButton: {
    backgroundColor: theme.colors.background.secondary,
    marginTop: 16,
    height: 52,
    justifyContent: "center",
    alignItems: "center",
  },
  cancelButtonText: {
    color: theme.colors.text.secondary,
    fontWeight: "500",
    fontSize: 16,
    letterSpacing: 0.5,
  },
  menuOverlay: {
    flex: 1,
    backgroundColor: theme.colors.background.overlay,
    justifyContent: "flex-end",
    alignItems: "center",
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  menuContainer: {
    width: "92%",
    backgroundColor: theme.colors.background.primary,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingVertical: 20,
    paddingHorizontal: 20,
    ...theme.shadows.xl,
  },
  menuHandle: {
    width: 40,
    height: 4,
    backgroundColor: theme.colors.primary.beige,
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: 20,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 12,
  },
  menuIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F5EDE5",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 14,
  },
  menuText: {
    flex: 1,
    fontSize: 16,
    fontWeight: "400",
    color: "#6B5B4D",
    letterSpacing: 0.3,
  },
  menuDivider: {
    height: 1,
    backgroundColor: "#F0EBE3",
    marginVertical: 4,
  },
  cancelItem: {
    marginTop: 12,
    paddingVertical: 14,
    backgroundColor: "#F5EDE5",
    borderRadius: 12,
    justifyContent: "center",
  },
});

export default modalStyles;